<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="mrane" name="Test" tests="6" failures="2" timestamp="5 Oct 2018 12:38:07 GMT" time="3.985" errors="0">
  <testcase name="login" time="0.721" classname="LoginModuleTests.DataDrivenLoginTests"/>
  <testcase name="login" time="0.264" classname="LoginModuleTests.DataDrivenLoginTests"/>
  <testcase name="login" time="0.248" classname="LoginModuleTests.DataDrivenLoginTests"/>
  <testcase name="invalidLogin" time="1.217" classname="LoginModuleTests.LoginTests">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
	at LoginModuleTests.LoginTests.invalidLogin(LoginTests.java:36)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- invalidLogin -->
  <testcase name="invalidLogin" time="1.235" classname="LoginModuleTests.LoginTests">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at listeners.TestListener.onTestFailure(TestListener.java:53)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 7 stack frames]]>
    </failure>
  </testcase> <!-- invalidLogin -->
  <testcase name="login" time="0.274" classname="LoginModuleTests.DataDrivenLoginTests"/>
</testsuite> <!-- Test -->
